# Generated by Django 6.0.7 on 2026-08-01 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=200)),
                ('cash_flow_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('loan_given', 'Loan Given'), ('loan_taken', 'Loan Taken')], max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared')], default='pending', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
