# Generated by Django 6.0.7 on 2026-07-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
