# Generated by Django 6.0.7 on 2026-08-07 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_playerskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_press', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shoulder_press', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deadlift', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weighted_squats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_pushups', models.PositiveIntegerField(blank=True, null=True)),
                ('max_pullups', models.PositiveIntegerField(blank=True, null=True)),
                ('max_russian_crunches', models.PositiveIntegerField(blank=True, null=True)),
                ('run_5km_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('run_5km_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
